#!/bin/bash

# Copyright (c)2015 Phil Estes <estesp@gmail.com>
# See LICENSE for MIT License terms

# See Dockerfile for context in which dockompleter.sh is used
#
# * Getting the .a files on your host $GOPATH:
# Example: given a host $GOPATH containing ~/go, you can 
# populate the auto-complete files in ~/go/pkg/linux_amd64
# by bind-mounting your go/pkg dir when running the 
# container in which this script runs:
#  docker run -v ~user/pkg:/go/pkg
DOCKER_ROOT=/go/src/github.com/docker/docker
DOTA_DEST=/go/pkg/linux_amd64

mkdir -p ${DOTA_DEST}

cd ${DOCKER_ROOT}

rm -rf autogen
mkdir -p autogen/dockerversion
cat > autogen/dockerversion/dockerversion.go <<EOF
// AUTOGENERATED FILE; see $BASH_SOURCE
package dockerversion

var (
    GITCOMMIT string = "donotuse"
    VERSION   string = "donotuse"

    IAMSTATIC string = "true"
    INITSHA1  string = "donotuse"
    INITPATH  string = "donotuse"
)
EOF

go build \
    -o /docker-binary \
    -work -a -tags "netgo daemon static_build btrfs_noversion" -installsuffix netgo \
    ./docker

cd /tmp/go-build*
cp -a github.com ${DOTA_DEST}
